In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("owid-covid-data.csv")
df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429430,ZWE,Africa,Zimbabwe,2024-07-31,266386.0,0.0,0.0,5740.0,0.0,0.0,...,30.7,36.79,1.7,61.49,0.57,16320539,NaN,NaN,NaN,NaN
429431,ZWE,Africa,Zimbabwe,2024-08-01,266386.0,0.0,0.0,5740.0,0.0,0.0,...,30.7,36.79,1.7,61.49,0.57,16320539,NaN,NaN,NaN,NaN
429432,ZWE,Africa,Zimbabwe,2024-08-02,266386.0,0.0,0.0,5740.0,0.0,0.0,...,30.7,36.79,1.7,61.49,0.57,16320539,NaN,NaN,NaN,NaN
429433,ZWE,Africa,Zimbabwe,2024-08-03,266386.0,0.0,0.0,5740.0,0.0,0.0,...,30.7,36.79,1.7,61.49,0.57,16320539,NaN,NaN,NaN,NaN
429434,ZWE,Africa,Zimbabwe,2024-08-04,266386.0,0.0,0.0,5740.0,0.0,0.0,...,30.7,36.79,1.7,61.49,0.57,16320539,NaN,NaN,NaN,NaN

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 429435 entries, 0 to 429434
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    429435 non-null  str
 1   continent                                   402910 non-null  str
 2   location                                    429435 non-null  str
 3   date                                        429435 non-null  str
 4   total_cases                                 411804 non-null  float64
 5   new_cases                                   410159 non-null  float64
 6   new_cases_smoothed                          408929 non-null  float64
 7   total_deaths                                411804 non-null  float64
 8   new_deaths                                  410608 non-null  float64
 9   new_deaths_smoothed                         409378 non-null  float64
 10  total_cases_per_million                     411804 non-null  float64
 11  new_cases_per_million                       410159 non-null  float64
 12  new_cases_smoothed_per_million              408929 non-null  float64
 13  total_deaths_per_million                    411804 non-null  float64
 14  new_deaths_per_million                      410608 non-null  float64
 15  new_deaths_smoothed_per_million             409378 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                39116 non-null   float64
 18  icu_patients_per_million                    39116 non-null   float64
 19  hosp_patients                               40656 non-null   float64
 20  hosp_patients_per_million                   40656 non-null   float64
 21  weekly_icu_admissions                       10993 non-null   float64
 22  weekly_icu_admissions_per_million           10993 non-null   float64
 23  weekly_hosp_admissions                      24497 non-null   float64
 24  weekly_hosp_admissions_per_million          24497 non-null   float64
 25  total_tests                                 79387 non-null   float64
 26  new_tests                                   75403 non-null   float64
 27  total_tests_per_thousand                    79387 non-null   float64
 28  new_tests_per_thousand                      75403 non-null   float64
 29  new_tests_smoothed                          103965 non-null  float64
 30  new_tests_smoothed_per_thousand             103965 non-null  float64
 31  positive_rate                               95927 non-null   float64
 32  tests_per_case                              94348 non-null   float64
 33  tests_units                                 106788 non-null  str
 34  total_vaccinations                          85417 non-null   float64
 35  people_vaccinated                           81132 non-null   float64
 36  people_fully_vaccinated                     78061 non-null   float64
 37  total_boosters                              53600 non-null   float64
 38  new_vaccinations                            70971 non-null   float64
 39  new_vaccinations_smoothed                   195029 non-null  float64
 40  total_vaccinations_per_hundred              85417 non-null   float64
 41  people_vaccinated_per_hundred               81132 non-null   float64
 42  people_fully_vaccinated_per_hundred         78061 non-null   float64
 43  total_boosters_per_hundred                  53600 non-null   float64
 44  new_vaccinations_smoothed_per_million       195029 non-null  float64
 45  new_people_vaccinated_smoothed              192177 non-null  float64
 46  new_people_vaccinated_smoothed_per_hundred  192177 non-null  float64
 47  stringency_index                            196190 non-null  float64
 48  population_density                          360492 non-null  float64
 49  median_age                                  334663 non-null  float64
 50  aged_65_older                               323270 non-null  float64
 51  aged_70_older                               331315 non-null  float64
 52  gdp_per_capita                              328292 non-null  float64
 53  extreme_poverty                             211996 non-null  float64
 54  cardiovasc_death_rate                       328865 non-null  float64
 55  diabetes_prevalence                         345911 non-null  float64
 56  female_smokers                              247165 non-null  float64
 57  male_smokers                                243817 non-null  float64
 58  handwashing_facilities                      161741 non-null  float64
 59  hospital_beds_per_thousand                  290689 non-null  float64
 60  life_expectancy                             390299 non-null  float64
 61  human_development_index                     319127 non-null  float64
 62  population                                  429435 non-null  int64
 63  excess_mortality_cumulative_absolute        13411 non-null   float64
 64  excess_mortality_cumulative                 13411 non-null   float64
 65  excess_mortality                            13411 non-null   float64
 66  excess_mortality_cumulative_per_million     13411 non-null   float64
dtypes: float64(61), int64(1), str(5)
memory usage: 219.5 MB

In [18]:
columns_needed = [
    "location",
    "continent",
    "date",
    "total_cases",
    "new_cases",
    "total_deaths",
    "new_deaths",
    "total_vaccinations",
    "population"
]

df = df[columns_needed]
df

,location,continent,date,total_cases,new_cases,total_deaths,new_deaths,total_vaccinations,population
0,Afghanistan,Asia,2020-01-05,0.0,0.0,0.0,0.0,0.0,41128772
1,Afghanistan,Asia,2020-01-06,0.0,0.0,0.0,0.0,0.0,41128772
2,Afghanistan,Asia,2020-01-07,0.0,0.0,0.0,0.0,0.0,41128772
3,Afghanistan,Asia,2020-01-08,0.0,0.0,0.0,0.0,0.0,41128772
4,Afghanistan,Asia,2020-01-09,0.0,0.0,0.0,0.0,0.0,41128772
...,...,...,...,...,...,...,...,...,...
429430,Zimbabwe,Africa,2024-07-31,266386.0,0.0,5740.0,0.0,0.0,16320539
429431,Zimbabwe,Africa,2024-08-01,266386.0,0.0,5740.0,0.0,0.0,16320539
429432,Zimbabwe,Africa,2024-08-02,266386.0,0.0,5740.0,0.0,0.0,16320539
429433,Zimbabwe,Africa,2024-08-03,266386.0,0.0,5740.0,0.0,0.0,16320539
429434,Zimbabwe,Africa,2024-08-04,266386.0,0.0,5740.0,0.0,0.0,16320539

In [16]:
df = df.dropna(subset=["location", "date"])
df = df.dropna()
df = df.fillna(0)
df = df.drop_duplicates()
df

,location,continent,date,total_cases,new_cases,total_deaths,new_deaths,total_vaccinations,population
0,Afghanistan,Asia,2020-01-05,0.0,0.0,0.0,0.0,0.0,41128772
1,Afghanistan,Asia,2020-01-06,0.0,0.0,0.0,0.0,0.0,41128772
2,Afghanistan,Asia,2020-01-07,0.0,0.0,0.0,0.0,0.0,41128772
3,Afghanistan,Asia,2020-01-08,0.0,0.0,0.0,0.0,0.0,41128772
4,Afghanistan,Asia,2020-01-09,0.0,0.0,0.0,0.0,0.0,41128772
...,...,...,...,...,...,...,...,...,...
429430,Zimbabwe,Africa,2024-07-31,266386.0,0.0,5740.0,0.0,0.0,16320539
429431,Zimbabwe,Africa,2024-08-01,266386.0,0.0,5740.0,0.0,0.0,16320539
429432,Zimbabwe,Africa,2024-08-02,266386.0,0.0,5740.0,0.0,0.0,16320539
429433,Zimbabwe,Africa,2024-08-03,266386.0,0.0,5740.0,0.0,0.0,16320539
429434,Zimbabwe,Africa,2024-08-04,266386.0,0.0,5740.0,0.0,0.0,16320539

In [15]:
df["date"] = pd.to_datetime(df["date"])
df

,location,continent,date,total_cases,new_cases,total_deaths,new_deaths,total_vaccinations,population
0,Afghanistan,Asia,2020-01-05,0.0,0.0,0.0,0.0,0.0,41128772
1,Afghanistan,Asia,2020-01-06,0.0,0.0,0.0,0.0,0.0,41128772
2,Afghanistan,Asia,2020-01-07,0.0,0.0,0.0,0.0,0.0,41128772
3,Afghanistan,Asia,2020-01-08,0.0,0.0,0.0,0.0,0.0,41128772
4,Afghanistan,Asia,2020-01-09,0.0,0.0,0.0,0.0,0.0,41128772
...,...,...,...,...,...,...,...,...,...
429430,Zimbabwe,Africa,2024-07-31,266386.0,0.0,5740.0,0.0,0.0,16320539
429431,Zimbabwe,Africa,2024-08-01,266386.0,0.0,5740.0,0.0,0.0,16320539
429432,Zimbabwe,Africa,2024-08-02,266386.0,0.0,5740.0,0.0,0.0,16320539
429433,Zimbabwe,Africa,2024-08-03,266386.0,0.0,5740.0,0.0,0.0,16320539
429434,Zimbabwe,Africa,2024-08-04,266386.0,0.0,5740.0,0.0,0.0,16320539

In [19]:
df = df.sort_values(by=["location", "date"])
df

,location,continent,date,total_cases,new_cases,total_deaths,new_deaths,total_vaccinations,population
0,Afghanistan,Asia,2020-01-05,0.0,0.0,0.0,0.0,0.0,41128772
1,Afghanistan,Asia,2020-01-06,0.0,0.0,0.0,0.0,0.0,41128772
2,Afghanistan,Asia,2020-01-07,0.0,0.0,0.0,0.0,0.0,41128772
3,Afghanistan,Asia,2020-01-08,0.0,0.0,0.0,0.0,0.0,41128772
4,Afghanistan,Asia,2020-01-09,0.0,0.0,0.0,0.0,0.0,41128772
...,...,...,...,...,...,...,...,...,...
429430,Zimbabwe,Africa,2024-07-31,266386.0,0.0,5740.0,0.0,0.0,16320539
429431,Zimbabwe,Africa,2024-08-01,266386.0,0.0,5740.0,0.0,0.0,16320539
429432,Zimbabwe,Africa,2024-08-02,266386.0,0.0,5740.0,0.0,0.0,16320539
429433,Zimbabwe,Africa,2024-08-03,266386.0,0.0,5740.0,0.0,0.0,16320539
429434,Zimbabwe,Africa,2024-08-04,266386.0,0.0,5740.0,0.0,0.0,16320539

In [20]:
df = df.sort_values(by=["location", "date"])

df = df[df["total_cases"] > 0]

df

,location,continent,date,total_cases,new_cases,total_deaths,new_deaths,total_vaccinations,population
56,Afghanistan,Asia,2020-03-01,1.0,1.0,0.0,0.0,0.0,41128772
57,Afghanistan,Asia,2020-03-02,1.0,0.0,0.0,0.0,0.0,41128772
58,Afghanistan,Asia,2020-03-03,1.0,0.0,0.0,0.0,0.0,41128772
59,Afghanistan,Asia,2020-03-04,1.0,0.0,0.0,0.0,0.0,41128772
60,Afghanistan,Asia,2020-03-05,1.0,0.0,0.0,0.0,0.0,41128772
...,...,...,...,...,...,...,...,...,...
429430,Zimbabwe,Africa,2024-07-31,266386.0,0.0,5740.0,0.0,0.0,16320539
429431,Zimbabwe,Africa,2024-08-01,266386.0,0.0,5740.0,0.0,0.0,16320539
429432,Zimbabwe,Africa,2024-08-02,266386.0,0.0,5740.0,0.0,0.0,16320539
429433,Zimbabwe,Africa,2024-08-03,266386.0,0.0,5740.0,0.0,0.0,16320539
429434,Zimbabwe,Africa,2024-08-04,266386.0,0.0,5740.0,0.0,0.0,16320539

In [22]:
df = df[
    (df["new_cases"] > 0) |
    (df["new_deaths"] > 0) |
    (df["total_vaccinations"] > 0)
]
df

,location,continent,date,total_cases,new_cases,total_deaths,new_deaths,total_vaccinations,population
56,Afghanistan,Asia,2020-03-01,1.0,1.0,0.0,0.0,0.0,41128772
70,Afghanistan,Asia,2020-03-15,7.0,6.0,0.0,0.0,0.0,41128772
77,Afghanistan,Asia,2020-03-22,24.0,17.0,0.0,0.0,0.0,41128772
84,Afghanistan,Asia,2020-03-29,91.0,67.0,2.0,2.0,0.0,41128772
91,Afghanistan,Asia,2020-04-05,274.0,183.0,5.0,3.0,0.0,41128772
...,...,...,...,...,...,...,...,...,...
429385,Zimbabwe,Africa,2024-06-16,266374.0,9.0,5740.0,0.0,0.0,16320539
429392,Zimbabwe,Africa,2024-06-23,266378.0,4.0,5740.0,0.0,0.0,16320539
429399,Zimbabwe,Africa,2024-06-30,266384.0,6.0,5740.0,0.0,0.0,16320539
429406,Zimbabwe,Africa,2024-07-07,266385.0,1.0,5740.0,0.0,0.0,16320539
429420,Zimbabwe,Africa,2024-07-21,266386.0,1.0,5740.0,0.0,0.0,16320539

In [24]:
df.to_excel("cleaned_covid_data.xlsx", index=False)